using FastEndpoints;using MediatR;using C=OrderFlow.Catalog.Application.Categories.CategoryFeatures;using P=OrderFlow.Catalog.Application.Products.ProductFeatures;namespace OrderFlow.Catalog.Api.Endpoints;public static class CatalogEndpoints
{
 public class IdRequest{public Guid Id{get;set;}} public sealed class ProductRequest:IdRequest{public string Sku{get;set;}=string.Empty;public string Name{get;set;}=string.Empty;public string? Description{get;set;}public decimal Price{get;set;}public Guid CategoryId{get;set;}} public sealed class ListRequest{public int Page{get;set;}=1;public int PageSize{get;set;}=20;public string? Search{get;set;}public string? Sort{get;set;}}public sealed class PriceRequest:IdRequest{public decimal Price{get;set;}}public sealed class CategoryRequest:IdRequest{public string Name{get;set;}=string.Empty;public string? Description{get;set;}}
 public sealed class CreateProduct(ISender s):Endpoint<ProductRequest,P.Dto>{public override void Configure(){Post("/api/products");AllowAnonymous();}public override async Task HandleAsync(ProductRequest r,CancellationToken ct)=>await Send.ResponseAsync(await s.Send(new P.Create(r.Sku,r.Name,r.Description,r.Price,r.CategoryId),ct),201,ct);}
 public sealed class GetProduct(ISender s):Endpoint<IdRequest,P.Dto>{public override void Configure(){Get("/api/products/{id}");AllowAnonymous();}public override async Task HandleAsync(IdRequest r,CancellationToken ct)=>await Send.OkAsync(await s.Send(new P.GetById(r.Id),ct),ct);}
 public sealed class ListProducts(ISender s):Endpoint<ListRequest,IReadOnlyList<P.Dto>>{public override void Configure(){Get("/api/products");AllowAnonymous();}public override async Task HandleAsync(ListRequest r,CancellationToken ct)=>await Send.OkAsync(await s.Send(new P.GetAll(r.Page,r.PageSize,r.Search,r.Sort),ct),ct);}
 public sealed class UpdateProduct(ISender s):Endpoint<ProductRequest,P.Dto>{public override void Configure(){Put("/api/products/{id}");AllowAnonymous();}public override async Task HandleAsync(ProductRequest r,CancellationToken ct)=>await Send.OkAsync(await s.Send(new P.Update(r.Id,r.Name,r.Description,r.CategoryId),ct),ct);}
 public sealed class ChangePrice(ISender s):Endpoint<PriceRequest,P.Dto>{public override void Configure(){Patch("/api/products/{id}/price");AllowAnonymous();}public override async Task HandleAsync(PriceRequest r,CancellationToken ct)=>await Send.OkAsync(await s.Send(new P.ChangePrice(r.Id,r.Price),ct),ct);}
 public sealed class Activate(ISender s):Endpoint<IdRequest>{public override void Configure(){Post("/api/products/{id}/activate");AllowAnonymous();}public override async Task HandleAsync(IdRequest r,CancellationToken ct){await s.Send(new P.Activate(r.Id),ct);await Send.NoContentAsync(ct);}}
 public sealed class Deactivate(ISender s):Endpoint<IdRequest>{public override void Configure(){Post("/api/products/{id}/deactivate");AllowAnonymous();}public override async Task HandleAsync(IdRequest r,CancellationToken ct){await s.Send(new P.Deactivate(r.Id),ct);await Send.NoContentAsync(ct);}}
 public sealed class Archive(ISender s):Endpoint<IdRequest>{public override void Configure(){Delete("/api/products/{id}");AllowAnonymous();}public override async Task HandleAsync(IdRequest r,CancellationToken ct){await s.Send(new P.Archive(r.Id),ct);await Send.NoContentAsync(ct);}}
 public sealed class CreateCategory(ISender s):Endpoint<CategoryRequest,C.Dto>{public override void Configure(){Post("/api/categories");AllowAnonymous();}public override async Task HandleAsync(CategoryRequest r,CancellationToken ct)=>await Send.ResponseAsync(await s.Send(new C.Create(r.Name,r.Description),ct),201,ct);}
 public sealed class ListCategories(ISender s):EndpointWithoutRequest<IReadOnlyList<C.Dto>>{public override void Configure(){Get("/api/categories");AllowAnonymous();}public override async Task HandleAsync(CancellationToken ct)=>await Send.OkAsync(await s.Send(new C.GetAll(),ct),ct);}
 public sealed class UpdateCategory(ISender s):Endpoint<CategoryRequest,C.Dto>{public override void Configure(){Put("/api/categories/{id}");AllowAnonymous();}public override async Task HandleAsync(CategoryRequest r,CancellationToken ct)=>await Send.OkAsync(await s.Send(new C.Update(r.Id,r.Name,r.Description),ct),ct);}
}

