using System.Text.Json; using Microsoft.EntityFrameworkCore; using OrderFlow.IntegrationContracts; using OrderFlow.Ordering.Domain.Common; using OrderFlow.Ordering.Domain.Orders;
namespace OrderFlow.Ordering.Infrastructure.Persistence;
public sealed class OrderingDbContext(DbContextOptions<OrderingDbContext> options):DbContext(options)
{
 public DbSet<Order> Orders=>Set<Order>();public DbSet<OrderItem> OrderItems=>Set<OrderItem>();public DbSet<OutboxMessage> OutboxMessages=>Set<OutboxMessage>();public DbSet<InboxMessage> InboxMessages=>Set<InboxMessage>();
 public override async Task<int> SaveChangesAsync(CancellationToken ct=default){var roots=ChangeTracker.Entries<AggregateRoot>().Select(x=>x.Entity).Where(x=>x.DomainEvents.Count>0).ToArray();foreach(var root in roots){foreach(var e in root.DomainEvents){object? payload=e switch{OrderSubmittedDomainEvent x=>new OrderSubmittedIntegrationEvent(x.OrderId,x.CustomerId,x.CustomerEmail,x.Items.Select(i=>new OrderItemContract(i.ProductId,i.ProductName,i.UnitPrice,i.Quantity)).ToArray(),x.TotalAmount),PaymentRequestedDomainEvent x=>new PaymentRequestedIntegrationEvent(x.OrderId,x.Amount),OrderConfirmedDomainEvent x=>new OrderConfirmedIntegrationEvent(x.OrderId,x.CustomerId,x.CustomerEmail),OrderCancelledDomainEvent x=>new OrderCancelledIntegrationEvent(x.OrderId,x.CustomerEmail,x.Reason),_=>null};if(payload is null)continue;var env=new IntegrationEventEnvelope(e.EventId,payload.GetType().Name,1,e.OccurredOnUtc,System.Diagnostics.Activity.Current?.TraceId.ToString()??e.EventId.ToString(),System.Diagnostics.Activity.Current?.SpanId.ToString(),root.Id.ToString(),JsonSerializer.Serialize(payload,payload.GetType()));OutboxMessages.Add(new(){Id=e.EventId,Type=KafkaTopics.OrderEvents,AggregateId=root.Id.ToString(),OccurredOnUtc=e.OccurredOnUtc,Content=JsonSerializer.Serialize(env)});}root.ClearDomainEvents();}return await base.SaveChangesAsync(ct);}
 protected override void OnModelCreating(ModelBuilder m){m.Entity<Order>(b=>{b.ToTable("orders");b.HasKey(x=>x.Id);b.Property(x=>x.CustomerEmail).HasConversion(x=>x.Value,x=>EmailAddress.Create(x)).HasMaxLength(320);b.Property(x=>x.Status).HasConversion(x=>x.Value,x=>OrderStatus.FromValue(x));b.Ignore(x=>x.DomainEvents);b.Ignore(x=>x.TotalAmount);b.OwnsOne(x=>x.ShippingAddress,a=>{a.Property(x=>x.Line1).HasColumnName("shipping_line1").HasMaxLength(300);a.Property(x=>x.City).HasColumnName("shipping_city").HasMaxLength(120);a.Property(x=>x.PostalCode).HasColumnName("shipping_postal_code").HasMaxLength(30);a.Property(x=>x.Country).HasColumnName("shipping_country").HasMaxLength(100);});b.HasMany(x=>x.Items).WithOne().HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade);b.HasIndex(x=>new{x.CustomerId,x.CreatedAt});b.Property(x=>x.Version).IsRowVersion();});m.Entity<OrderItem>(b=>{b.ToTable("order_items");b.HasKey(x=>x.Id);b.Property(x=>x.ProductName).HasMaxLength(200);b.Property(x=>x.UnitPrice).HasPrecision(18,2);b.Ignore(x=>x.Total);});ConfigureMessaging(m);}
 private static void ConfigureMessaging(ModelBuilder m){m.Entity<OutboxMessage>(b=>{b.ToTable("outbox_messages");b.HasKey(x=>x.Id);b.Property(x=>x.Type).HasMaxLength(250);b.Property(x=>x.Content).HasColumnType("jsonb");b.Property(x=>x.AggregateId).HasMaxLength(100);b.Property(x=>x.Error).HasMaxLength(2000);b.HasIndex(x=>new{x.ProcessedOnUtc,x.OccurredOnUtc});});m.Entity<InboxMessage>(b=>{b.ToTable("inbox_messages");b.HasKey(x=>new{x.Id,x.Consumer});b.Property(x=>x.Consumer).HasMaxLength(200);});}
}
