using MediatR; using OrderFlow.Ordering.Application.Abstractions.Errors; using OrderFlow.Ordering.Application.Abstractions.Messaging; using OrderFlow.Ordering.Application.Abstractions.Persistence; using OrderFlow.Ordering.Domain.Orders;
namespace OrderFlow.Ordering.Application.Orders;
public static class OrderFeatures
{
    public sealed record Address(string Line1,string City,string PostalCode,string Country); public sealed record Item(Guid Id,Guid ProductId,string ProductName,decimal UnitPrice,int Quantity,decimal Total); public sealed record Dto(Guid Id,Guid CustomerId,string CustomerEmail,Address ShippingAddress,IReadOnlyList<Item> Items,decimal TotalAmount,string Status,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt);
    public sealed record Create(Guid CustomerId,string CustomerEmail,Address ShippingAddress):ICommand<Dto>; public sealed class CreateHandler(IOrderRepository r):IRequestHandler<Create,Dto>{public async Task<Dto> Handle(Create c,CancellationToken ct){var a=ShippingAddress.Create(c.ShippingAddress.Line1,c.ShippingAddress.City,c.ShippingAddress.PostalCode,c.ShippingAddress.Country);var x=Order.Create(c.CustomerId,c.CustomerEmail,a);await r.AddAsync(x,ct);return Map(x);}}
    public sealed record AddItem(Guid OrderId,Guid ProductId,string ProductName,decimal UnitPrice,int Quantity):ICommand<Dto>; public sealed class AddItemHandler(IOrderRepository r):IRequestHandler<AddItem,Dto>{public async Task<Dto> Handle(AddItem c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.AddItem(c.ProductId,c.ProductName,c.UnitPrice,c.Quantity);await r.SaveAsync(ct);return Map(x);}}
    public sealed record RemoveItem(Guid OrderId,Guid ItemId):ICommand<Dto>; public sealed class RemoveItemHandler(IOrderRepository r):IRequestHandler<RemoveItem,Dto>{public async Task<Dto> Handle(RemoveItem c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.RemoveItem(c.ItemId);await r.SaveAsync(ct);return Map(x);}}
    public sealed record Submit(Guid OrderId):ICommand<Dto>; public sealed class SubmitHandler(IOrderRepository r):IRequestHandler<Submit,Dto>{public async Task<Dto> Handle(Submit c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.Submit();await r.SaveAsync(ct);return Map(x);}}
    public sealed record GetById(Guid Id):IQuery<Dto>; public sealed class GetByIdHandler(IOrderRepository r):IRequestHandler<GetById,Dto>{public async Task<Dto> Handle(GetById q,CancellationToken ct)=>Map(await Find(r,q.Id,ct));}
    public sealed record GetCustomerOrders(Guid CustomerId):IQuery<IReadOnlyList<Dto>>; public sealed class GetCustomerOrdersHandler(IOrderRepository r):IRequestHandler<GetCustomerOrders,IReadOnlyList<Dto>>{public async Task<IReadOnlyList<Dto>> Handle(GetCustomerOrders q,CancellationToken ct)=>(await r.GetCustomerOrdersAsync(q.CustomerId,ct)).Select(Map).ToArray();}
    public sealed record Cancel(Guid OrderId,string Reason):ICommand<Dto>; public sealed class CancelHandler(IOrderRepository r):IRequestHandler<Cancel,Dto>{public async Task<Dto> Handle(Cancel c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.Cancel(c.Reason);await r.SaveAsync(ct);return Map(x);}}
    public sealed record InventoryReserved(Guid OrderId):ICommand; public sealed class InventoryReservedHandler(IOrderRepository r):IRequestHandler<InventoryReserved>{public async Task Handle(InventoryReserved c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.MarkInventoryReserved();await r.SaveAsync(ct);}}
    public sealed record PaymentSucceeded(Guid OrderId):ICommand; public sealed class PaymentSucceededHandler(IOrderRepository r):IRequestHandler<PaymentSucceeded>{public async Task Handle(PaymentSucceeded c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.ConfirmPayment();await r.SaveAsync(ct);}}
    public sealed record WorkflowFailed(Guid OrderId,string Reason):ICommand; public sealed class WorkflowFailedHandler(IOrderRepository r):IRequestHandler<WorkflowFailed>{public async Task Handle(WorkflowFailed c,CancellationToken ct){var x=await Find(r,c.OrderId,ct);x.Cancel(c.Reason);await r.SaveAsync(ct);}}
    private static async Task<Order> Find(IOrderRepository r,Guid id,CancellationToken ct)=>await r.GetAsync(id,ct)??throw new NotFoundException("Order was not found."); private static Dto Map(Order x)=>new(x.Id,x.CustomerId,x.CustomerEmail.Value,new(x.ShippingAddress.Line1,x.ShippingAddress.City,x.ShippingAddress.PostalCode,x.ShippingAddress.Country),x.Items.Select(i=>new Item(i.Id,i.ProductId,i.ProductName,i.UnitPrice,i.Quantity,i.Total)).ToArray(),x.TotalAmount,x.Status.Name,x.CreatedAt,x.UpdatedAt);
}
