using MediatR; using OrderFlow.Notifications.Application.Abstractions.Delivery; using OrderFlow.Notifications.Application.Abstractions.Errors; using OrderFlow.Notifications.Application.Abstractions.Messaging; using OrderFlow.Notifications.Application.Abstractions.Persistence; using OrderFlow.Notifications.Domain.Notifications;
namespace OrderFlow.Notifications.Application.Notifications;
public static class NotificationFeatures
{
    public sealed record Attempt(Guid Id,bool Succeeded,string? Error,DateTimeOffset AttemptedAt); public sealed record Dto(Guid Id,string Recipient,string Subject,string Body,string Channel,string Status,IReadOnlyList<Attempt> Attempts,DateTimeOffset CreatedAt,DateTimeOffset? SentAt);
    public sealed record Create(string Recipient,string Subject,string Body,string Channel):ICommand<Dto>; public sealed class CreateHandler(INotificationRepository r):IRequestHandler<Create,Dto>{public async Task<Dto> Handle(Create c,CancellationToken ct){var x=Notification.Create(c.Recipient,c.Subject,c.Body,NotificationChannel.FromName(c.Channel,true));await r.AddAsync(x,ct);return Map(x);}}
    public sealed record Send(Guid Id):ICommand<Dto>; public sealed class SendHandler(INotificationRepository r,IEmailSender sender):IRequestHandler<Send,Dto>{public async Task<Dto> Handle(Send c,CancellationToken ct){var x=await Find(r,c.Id,ct);x.StartSending();try{await sender.SendAsync(x.Recipient,x.Subject,x.Body,ct);x.RecordSuccess();}catch(Exception ex) when(ex is not OperationCanceledException){x.RecordFailure(ex.Message);}await r.SaveAsync(ct);return Map(x);}}
    public sealed record Retry(Guid Id):ICommand<Dto>; public sealed class RetryHandler(IMediator mediator):IRequestHandler<Retry,Dto>{public Task<Dto> Handle(Retry c,CancellationToken ct)=>mediator.Send(new Send(c.Id),ct);}
    public sealed record Get(Guid Id):IQuery<Dto>; public sealed class GetHandler(INotificationRepository r):IRequestHandler<Get,Dto>{public async Task<Dto> Handle(Get q,CancellationToken ct)=>Map(await Find(r,q.Id,ct));}
    public sealed record GetForRecipient(string Recipient):IQuery<IReadOnlyList<Dto>>; public sealed class GetForRecipientHandler(INotificationRepository r):IRequestHandler<GetForRecipient,IReadOnlyList<Dto>>{public async Task<IReadOnlyList<Dto>> Handle(GetForRecipient q,CancellationToken ct)=>(await r.GetForRecipientAsync(q.Recipient,ct)).Select(Map).ToArray();}
    private static async Task<Notification> Find(INotificationRepository r,Guid id,CancellationToken ct)=>await r.GetAsync(id,ct)??throw new NotFoundException("Notification was not found."); private static Dto Map(Notification x)=>new(x.Id,x.Recipient,x.Subject,x.Body,x.Channel.Name,x.Status.Name,x.Attempts.Select(a=>new Attempt(a.Id,a.Succeeded,a.Error,a.AttemptedAt)).ToArray(),x.CreatedAt,x.SentAt);
}
